// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';

export const missile: { [id: number]: number } = {};
missile[BOMBER_TYPE_ID] = -1;
missile[STEALTH_BOMBER_TYPE_ID] = -1;
missile[STEALTH_FIGHTER_TYPE_ID] = -1;
missile[AIR_REFUELING_SQUADRON_ID] = -1;
missile[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = -1;
missile[AIRBORN_ISR_TYPE_ID] = -1;
missile[ARMY_INFANTRY_COMPANY_TYPE_ID] = -1;
missile[ARTILLERY_BATTERY_TYPE_ID] = -1;
missile[TANK_COMPANY_TYPE_ID] = -1;
missile[MARINE_INFANTRY_COMPANY_TYPE_ID] = -1;
missile[ATTACK_HELICOPTER_TYPE_ID] = -1;
missile[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = -1;
missile[SAM_SITE_TYPE_ID] = -1;
missile[DESTROYER_TYPE_ID] = -1;
missile[A_C_CARRIER_TYPE_ID] = -1;
missile[SUBMARINE_TYPE_ID] = -1;
missile[TRANSPORT_TYPE_ID] = -1;
missile[MC_12_TYPE_ID] = -1;
missile[C_130_TYPE_ID] = -1;
missile[SOF_TEAM_TYPE_ID] = -1;
missile[RADAR_TYPE_ID] = -1;
missile[MISSILE_TYPE_ID] = -1;
