import { UNABLE_TO_SEE } from '../../globals';
// prettier-ignore
import { AIRBORN_ISR_TYPE_ID, AIR_REFUELING_SQUADRON_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, A_C_CARRIER_TYPE_ID, BOMBER_TYPE_ID, C_130_TYPE_ID, DESTROYER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, MC_12_TYPE_ID, MISSILE_TYPE_ID, RADAR_TYPE_ID, SAM_SITE_TYPE_ID, SOF_TEAM_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, SUBMARINE_TYPE_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, TANK_COMPANY_TYPE_ID, TRANSPORT_TYPE_ID } from '../../pieces/pieceId';

export const destroyer: { [id: number]: number } = {};
destroyer[BOMBER_TYPE_ID] = 0;
destroyer[STEALTH_BOMBER_TYPE_ID] = UNABLE_TO_SEE;
destroyer[STEALTH_FIGHTER_TYPE_ID] = UNABLE_TO_SEE;
destroyer[AIR_REFUELING_SQUADRON_ID] = 0;
destroyer[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = 0;
destroyer[AIRBORN_ISR_TYPE_ID] = 0;
destroyer[ARMY_INFANTRY_COMPANY_TYPE_ID] = 1;
destroyer[ARTILLERY_BATTERY_TYPE_ID] = 1;
destroyer[TANK_COMPANY_TYPE_ID] = 1;
destroyer[MARINE_INFANTRY_COMPANY_TYPE_ID] = 1;
destroyer[ATTACK_HELICOPTER_TYPE_ID] = 1;
destroyer[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 1;
destroyer[SAM_SITE_TYPE_ID] = 1;
destroyer[DESTROYER_TYPE_ID] = 1;
destroyer[A_C_CARRIER_TYPE_ID] = 1;
destroyer[SUBMARINE_TYPE_ID] = 1;
destroyer[TRANSPORT_TYPE_ID] = 1;
destroyer[MC_12_TYPE_ID] = 0;
destroyer[C_130_TYPE_ID] = 1;
destroyer[SOF_TEAM_TYPE_ID] = UNABLE_TO_SEE;
destroyer[RADAR_TYPE_ID] = 1;
destroyer[MISSILE_TYPE_ID] = UNABLE_TO_SEE;
