// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';
import { UNABLE_TO_SEE } from '../../globals';

export const transport: { [id: number]: number } = {};
transport[BOMBER_TYPE_ID] = 0;
transport[STEALTH_BOMBER_TYPE_ID] = UNABLE_TO_SEE;
transport[STEALTH_FIGHTER_TYPE_ID] = UNABLE_TO_SEE;
transport[AIR_REFUELING_SQUADRON_ID] = 0;
transport[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = 0;
transport[AIRBORN_ISR_TYPE_ID] = 0;
transport[ARMY_INFANTRY_COMPANY_TYPE_ID] = 0;
transport[ARTILLERY_BATTERY_TYPE_ID] = 0;
transport[TANK_COMPANY_TYPE_ID] = 0;
transport[MARINE_INFANTRY_COMPANY_TYPE_ID] = 0;
transport[ATTACK_HELICOPTER_TYPE_ID] = 0;
transport[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 0;
transport[SAM_SITE_TYPE_ID] = 0;
transport[DESTROYER_TYPE_ID] = 0;
transport[A_C_CARRIER_TYPE_ID] = 0;
transport[SUBMARINE_TYPE_ID] = UNABLE_TO_SEE;
transport[TRANSPORT_TYPE_ID] = 0;
transport[MC_12_TYPE_ID] = 0;
transport[C_130_TYPE_ID] = 0;
transport[SOF_TEAM_TYPE_ID] = UNABLE_TO_SEE;
transport[RADAR_TYPE_ID] = 0;
transport[MISSILE_TYPE_ID] = UNABLE_TO_SEE;
