import { UNABLE_TO_HIT } from '../../globals';
// prettier-ignore
import { AIRBORN_ISR_TYPE_ID, AIR_REFUELING_SQUADRON_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, A_C_CARRIER_TYPE_ID, BOMBER_TYPE_ID, C_130_TYPE_ID, DESTROYER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, MC_12_TYPE_ID, MISSILE_TYPE_ID, RADAR_TYPE_ID, SAM_SITE_TYPE_ID, SOF_TEAM_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, SUBMARINE_TYPE_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, TANK_COMPANY_TYPE_ID, TRANSPORT_TYPE_ID } from '../../pieces/pieceId';

export const c130: { [id: number]: number } = {};
c130[BOMBER_TYPE_ID] = UNABLE_TO_HIT;
c130[STEALTH_BOMBER_TYPE_ID] = UNABLE_TO_HIT;
c130[STEALTH_FIGHTER_TYPE_ID] = UNABLE_TO_HIT;
c130[AIR_REFUELING_SQUADRON_ID] = UNABLE_TO_HIT;
c130[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = UNABLE_TO_HIT;
c130[AIRBORN_ISR_TYPE_ID] = UNABLE_TO_HIT;
c130[ARMY_INFANTRY_COMPANY_TYPE_ID] = UNABLE_TO_HIT;
c130[ARTILLERY_BATTERY_TYPE_ID] = UNABLE_TO_HIT;
c130[TANK_COMPANY_TYPE_ID] = UNABLE_TO_HIT;
c130[MARINE_INFANTRY_COMPANY_TYPE_ID] = UNABLE_TO_HIT;
c130[ATTACK_HELICOPTER_TYPE_ID] = UNABLE_TO_HIT;
c130[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = UNABLE_TO_HIT;
c130[SAM_SITE_TYPE_ID] = UNABLE_TO_HIT;
c130[DESTROYER_TYPE_ID] = UNABLE_TO_HIT;
c130[A_C_CARRIER_TYPE_ID] = UNABLE_TO_HIT;
c130[SUBMARINE_TYPE_ID] = UNABLE_TO_HIT;
c130[TRANSPORT_TYPE_ID] = UNABLE_TO_HIT;
c130[MC_12_TYPE_ID] = UNABLE_TO_HIT;
c130[C_130_TYPE_ID] = UNABLE_TO_HIT;
c130[SOF_TEAM_TYPE_ID] = UNABLE_TO_HIT;
c130[RADAR_TYPE_ID] = UNABLE_TO_HIT;
c130[MISSILE_TYPE_ID] = UNABLE_TO_HIT;
