// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';
import { UNABLE_TO_SEE } from '../../globals';

export const radar: { [id: number]: number } = {};
radar[BOMBER_TYPE_ID] = 3;
radar[STEALTH_BOMBER_TYPE_ID] = 1;
radar[STEALTH_FIGHTER_TYPE_ID] = 1;
radar[AIR_REFUELING_SQUADRON_ID] = 3;
radar[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = 3;
radar[AIRBORN_ISR_TYPE_ID] = 3;
radar[ARMY_INFANTRY_COMPANY_TYPE_ID] = 1;
radar[ARTILLERY_BATTERY_TYPE_ID] = 2;
radar[TANK_COMPANY_TYPE_ID] = 2;
radar[MARINE_INFANTRY_COMPANY_TYPE_ID] = 1;
radar[ATTACK_HELICOPTER_TYPE_ID] = 2;
radar[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 2;
radar[SAM_SITE_TYPE_ID] = 2;
radar[DESTROYER_TYPE_ID] = 3;
radar[A_C_CARRIER_TYPE_ID] = 3;
radar[SUBMARINE_TYPE_ID] = UNABLE_TO_SEE;
radar[TRANSPORT_TYPE_ID] = 3;
radar[MC_12_TYPE_ID] = 2;
radar[C_130_TYPE_ID] = 2;
radar[SOF_TEAM_TYPE_ID] = 0;
radar[RADAR_TYPE_ID] = 3;
radar[MISSILE_TYPE_ID] = UNABLE_TO_SEE;
