// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';
import { UNABLE_TO_SEE } from '../../globals';

export const stealthBomber: { [id: number]: number } = {};
stealthBomber[BOMBER_TYPE_ID] = 1;
stealthBomber[STEALTH_BOMBER_TYPE_ID] = 0;
stealthBomber[STEALTH_FIGHTER_TYPE_ID] = UNABLE_TO_SEE;
stealthBomber[AIR_REFUELING_SQUADRON_ID] = 1;
stealthBomber[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = 1;
stealthBomber[AIRBORN_ISR_TYPE_ID] = 0;
stealthBomber[ARMY_INFANTRY_COMPANY_TYPE_ID] = 1;
stealthBomber[ARTILLERY_BATTERY_TYPE_ID] = 1;
stealthBomber[TANK_COMPANY_TYPE_ID] = 1;
stealthBomber[MARINE_INFANTRY_COMPANY_TYPE_ID] = 1;
stealthBomber[ATTACK_HELICOPTER_TYPE_ID] = 1;
stealthBomber[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 1;
stealthBomber[SAM_SITE_TYPE_ID] = 1;
stealthBomber[DESTROYER_TYPE_ID] = 2;
stealthBomber[A_C_CARRIER_TYPE_ID] = 2;
stealthBomber[SUBMARINE_TYPE_ID] = UNABLE_TO_SEE;
stealthBomber[TRANSPORT_TYPE_ID] = 2;
stealthBomber[MC_12_TYPE_ID] = 1;
stealthBomber[C_130_TYPE_ID] = 1;
stealthBomber[SOF_TEAM_TYPE_ID] = UNABLE_TO_SEE;
stealthBomber[RADAR_TYPE_ID] = 2;
stealthBomber[MISSILE_TYPE_ID] = UNABLE_TO_SEE;
