// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';
import { UNABLE_TO_SEE } from '../../globals';

export const tacAirliftSquad: { [id: number]: number } = {};
tacAirliftSquad[BOMBER_TYPE_ID] = 0;
tacAirliftSquad[STEALTH_BOMBER_TYPE_ID] = UNABLE_TO_SEE;
tacAirliftSquad[STEALTH_FIGHTER_TYPE_ID] = UNABLE_TO_SEE;
tacAirliftSquad[AIR_REFUELING_SQUADRON_ID] = 0;
tacAirliftSquad[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = 0;
tacAirliftSquad[AIRBORN_ISR_TYPE_ID] = 0;
tacAirliftSquad[ARMY_INFANTRY_COMPANY_TYPE_ID] = 0;
tacAirliftSquad[ARTILLERY_BATTERY_TYPE_ID] = 0;
tacAirliftSquad[TANK_COMPANY_TYPE_ID] = 0;
tacAirliftSquad[MARINE_INFANTRY_COMPANY_TYPE_ID] = UNABLE_TO_SEE;
tacAirliftSquad[ATTACK_HELICOPTER_TYPE_ID] = 0;
tacAirliftSquad[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 0;
tacAirliftSquad[SAM_SITE_TYPE_ID] = UNABLE_TO_SEE;
tacAirliftSquad[DESTROYER_TYPE_ID] = 0;
tacAirliftSquad[A_C_CARRIER_TYPE_ID] = 0;
tacAirliftSquad[SUBMARINE_TYPE_ID] = UNABLE_TO_SEE;
tacAirliftSquad[TRANSPORT_TYPE_ID] = 0;
tacAirliftSquad[MC_12_TYPE_ID] = 0;
tacAirliftSquad[C_130_TYPE_ID] = 1;
tacAirliftSquad[SOF_TEAM_TYPE_ID] = UNABLE_TO_SEE;
tacAirliftSquad[RADAR_TYPE_ID] = 0;
tacAirliftSquad[MISSILE_TYPE_ID] = UNABLE_TO_SEE;
