// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';

export const lightInfantry: { [id: number]: number } = {};
lightInfantry[BOMBER_TYPE_ID] = -1;
lightInfantry[STEALTH_BOMBER_TYPE_ID] = -1;
lightInfantry[STEALTH_FIGHTER_TYPE_ID] = -1;
lightInfantry[AIR_REFUELING_SQUADRON_ID] = -1;
lightInfantry[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = -1;
lightInfantry[AIRBORN_ISR_TYPE_ID] = -1;
lightInfantry[ARMY_INFANTRY_COMPANY_TYPE_ID] = 0;
lightInfantry[ARTILLERY_BATTERY_TYPE_ID] = 0;
lightInfantry[TANK_COMPANY_TYPE_ID] = 0;
lightInfantry[MARINE_INFANTRY_COMPANY_TYPE_ID] = 0;
lightInfantry[ATTACK_HELICOPTER_TYPE_ID] = 1;
lightInfantry[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 0;
lightInfantry[SAM_SITE_TYPE_ID] = 0;
lightInfantry[DESTROYER_TYPE_ID] = 0;
lightInfantry[A_C_CARRIER_TYPE_ID] = 0;
lightInfantry[SUBMARINE_TYPE_ID] = -1;
lightInfantry[TRANSPORT_TYPE_ID] = 0;
lightInfantry[MC_12_TYPE_ID] = -1;
lightInfantry[C_130_TYPE_ID] = -1;
lightInfantry[SOF_TEAM_TYPE_ID] = 0;
lightInfantry[RADAR_TYPE_ID] = 1;
lightInfantry[MISSILE_TYPE_ID] = -1;
