// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';

export const tankCompany: { [id: number]: number } = {};
tankCompany[BOMBER_TYPE_ID] = -1;
tankCompany[STEALTH_BOMBER_TYPE_ID] = -1;
tankCompany[STEALTH_FIGHTER_TYPE_ID] = -1;
tankCompany[AIR_REFUELING_SQUADRON_ID] = -1;
tankCompany[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = -1;
tankCompany[AIRBORN_ISR_TYPE_ID] = -1;
tankCompany[ARMY_INFANTRY_COMPANY_TYPE_ID] = 0;
tankCompany[ARTILLERY_BATTERY_TYPE_ID] = 0;
tankCompany[TANK_COMPANY_TYPE_ID] = 0;
tankCompany[MARINE_INFANTRY_COMPANY_TYPE_ID] = 0;
tankCompany[ATTACK_HELICOPTER_TYPE_ID] = 1;
tankCompany[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 0;
tankCompany[SAM_SITE_TYPE_ID] = 0;
tankCompany[DESTROYER_TYPE_ID] = 0;
tankCompany[A_C_CARRIER_TYPE_ID] = 0;
tankCompany[SUBMARINE_TYPE_ID] = -1;
tankCompany[TRANSPORT_TYPE_ID] = 0;
tankCompany[MC_12_TYPE_ID] = -1;
tankCompany[C_130_TYPE_ID] = -1;
tankCompany[SOF_TEAM_TYPE_ID] = 0;
tankCompany[RADAR_TYPE_ID] = 1;
tankCompany[MISSILE_TYPE_ID] = -1;
