export const BOMBER_TYPE_ID = 0;
export const STEALTH_BOMBER_TYPE_ID = 1;
export const STEALTH_FIGHTER_TYPE_ID = 2;
export const AIR_REFUELING_SQUADRON_ID = 3;
export const TACTICAL_AIRLIFT_SQUADRON_TYPE_ID = 4;
export const AIRBORN_ISR_TYPE_ID = 5;
export const ARMY_INFANTRY_COMPANY_TYPE_ID = 6;
export const ARTILLERY_BATTERY_TYPE_ID = 7;
export const TANK_COMPANY_TYPE_ID = 8;
export const MARINE_INFANTRY_COMPANY_TYPE_ID = 9;
export const ATTACK_HELICOPTER_TYPE_ID = 10;
export const LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID = 11;
export const SAM_SITE_TYPE_ID = 12;
export const DESTROYER_TYPE_ID = 13;
export const A_C_CARRIER_TYPE_ID = 14;
export const SUBMARINE_TYPE_ID = 15;
export const TRANSPORT_TYPE_ID = 16;
export const MC_12_TYPE_ID = 17;
export const C_130_TYPE_ID = 18;
export const SOF_TEAM_TYPE_ID = 19;
export const RADAR_TYPE_ID = 20;
export const MISSILE_TYPE_ID = 21;

export const ATC_SCRAMBLE_TYPE_ID = 22;
export const CYBER_DOMINANCE_TYPE_ID = 23;
export const MISSILE_LAUNCH_DISRUPTION_TYPE_ID = 24;
export const COMMUNICATIONS_INTERRUPTION_TYPE_ID = 25;
export const REMOTE_SENSING_TYPE_ID = 26;
export const RODS_FROM_GOD_TYPE_ID = 27;
export const ANTI_SATELLITE_MISSILES_TYPE_ID = 28;
export const GOLDEN_EYE_TYPE_ID = 29;
export const NUCLEAR_STRIKE_TYPE_ID = 30;
export const BIOLOGICAL_WEAPONS_TYPE_ID = 31;
export const SEA_MINES_TYPE_ID = 32;
export const DRONE_SWARMS_TYPE_ID = 33;
export const INSURGENCY_TYPE_ID = 34;
export const RAISE_MORALE_TYPE_ID = 35;
export const CYBER_DOM_CHECK_TYPE_ID = 36;

// prettier-ignore
export const LIST_ALL_PIECES = [BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID];
// prettier-ignore
export const LIST_ALL_CAPABILITIES = [ATC_SCRAMBLE_TYPE_ID, CYBER_DOMINANCE_TYPE_ID, CYBER_DOM_CHECK_TYPE_ID, MISSILE_LAUNCH_DISRUPTION_TYPE_ID, COMMUNICATIONS_INTERRUPTION_TYPE_ID, REMOTE_SENSING_TYPE_ID, RODS_FROM_GOD_TYPE_ID, ANTI_SATELLITE_MISSILES_TYPE_ID, GOLDEN_EYE_TYPE_ID, NUCLEAR_STRIKE_TYPE_ID, BIOLOGICAL_WEAPONS_TYPE_ID, SEA_MINES_TYPE_ID, DRONE_SWARMS_TYPE_ID, INSURGENCY_TYPE_ID, RAISE_MORALE_TYPE_ID];

export const LIST_ALL_AIRFIELD_PIECES = [
    BOMBER_TYPE_ID,
    STEALTH_BOMBER_TYPE_ID,
    STEALTH_FIGHTER_TYPE_ID,
    AIR_REFUELING_SQUADRON_ID,
    AIRBORN_ISR_TYPE_ID,
    TACTICAL_AIRLIFT_SQUADRON_TYPE_ID,
    MC_12_TYPE_ID,
    C_130_TYPE_ID
];
