import * as ID from './pieceId';

const LAND_TERRAIN_TYPE = 'land';
const WATER_TERRAIN_TYPE = 'water';
const AIRFIELD_TERRAIN_TYPE = 'airfield';
const MISSILE_TERRAIN_TYPE = 'missile';
const FLAG_TERRAIN_TYPE = 'flag';

export const ALL_TERRAIN = [LAND_TERRAIN_TYPE, WATER_TERRAIN_TYPE, AIRFIELD_TERRAIN_TYPE, MISSILE_TERRAIN_TYPE, FLAG_TERRAIN_TYPE];

export const GROUND_TERRAIN = [LAND_TERRAIN_TYPE, AIRFIELD_TERRAIN_TYPE, MISSILE_TERRAIN_TYPE, FLAG_TERRAIN_TYPE];

export const WATER_TERRAIN = [WATER_TERRAIN_TYPE];

// TODO: figure out a way to enforce that all piece types are used? (typescript) or that non-valid piece types not used.
export const TYPE_TERRAIN: { [id: number]: string[] } = {};
TYPE_TERRAIN[ID.BOMBER_TYPE_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.STEALTH_BOMBER_TYPE_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.STEALTH_FIGHTER_TYPE_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.AIR_REFUELING_SQUADRON_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.AIRBORN_ISR_TYPE_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.ARMY_INFANTRY_COMPANY_TYPE_ID] = [...GROUND_TERRAIN];
TYPE_TERRAIN[ID.ARTILLERY_BATTERY_TYPE_ID] = [...GROUND_TERRAIN];
TYPE_TERRAIN[ID.TANK_COMPANY_TYPE_ID] = [...GROUND_TERRAIN];
TYPE_TERRAIN[ID.MARINE_INFANTRY_COMPANY_TYPE_ID] = [...GROUND_TERRAIN];
TYPE_TERRAIN[ID.ATTACK_HELICOPTER_TYPE_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = [...GROUND_TERRAIN];
TYPE_TERRAIN[ID.SAM_SITE_TYPE_ID] = [...GROUND_TERRAIN];
TYPE_TERRAIN[ID.DESTROYER_TYPE_ID] = [...WATER_TERRAIN];
TYPE_TERRAIN[ID.A_C_CARRIER_TYPE_ID] = [...WATER_TERRAIN];
TYPE_TERRAIN[ID.SUBMARINE_TYPE_ID] = [...WATER_TERRAIN];
TYPE_TERRAIN[ID.TRANSPORT_TYPE_ID] = [...WATER_TERRAIN];
TYPE_TERRAIN[ID.MC_12_TYPE_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.C_130_TYPE_ID] = [...ALL_TERRAIN];
TYPE_TERRAIN[ID.SOF_TEAM_TYPE_ID] = [...GROUND_TERRAIN];
TYPE_TERRAIN[ID.RADAR_TYPE_ID] = [...GROUND_TERRAIN];
TYPE_TERRAIN[ID.MISSILE_TYPE_ID] = [MISSILE_TERRAIN_TYPE];
