// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';

export const artillery: { [id: number]: number } = {};
artillery[BOMBER_TYPE_ID] = 0;
artillery[STEALTH_BOMBER_TYPE_ID] = 0;
artillery[STEALTH_FIGHTER_TYPE_ID] = 0;
artillery[AIR_REFUELING_SQUADRON_ID] = 0;
artillery[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = 0;
artillery[AIRBORN_ISR_TYPE_ID] = 0;
artillery[ARMY_INFANTRY_COMPANY_TYPE_ID] = 6;
artillery[ARTILLERY_BATTERY_TYPE_ID] = 6;
artillery[TANK_COMPANY_TYPE_ID] = 8;
artillery[MARINE_INFANTRY_COMPANY_TYPE_ID] = 7;
artillery[ATTACK_HELICOPTER_TYPE_ID] = 0;
artillery[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 7;
artillery[SAM_SITE_TYPE_ID] = 4;
artillery[DESTROYER_TYPE_ID] = 0;
artillery[A_C_CARRIER_TYPE_ID] = 0;
artillery[SUBMARINE_TYPE_ID] = 0;
artillery[TRANSPORT_TYPE_ID] = 0;
artillery[MC_12_TYPE_ID] = 0;
artillery[C_130_TYPE_ID] = 0;
artillery[SOF_TEAM_TYPE_ID] = 4;
artillery[RADAR_TYPE_ID] = 5;
artillery[MISSILE_TYPE_ID] = 0;
