import { UNABLE_TO_HIT } from '../../globals';
// prettier-ignore
import { AIRBORN_ISR_TYPE_ID, AIR_REFUELING_SQUADRON_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, A_C_CARRIER_TYPE_ID, BOMBER_TYPE_ID, C_130_TYPE_ID, DESTROYER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, MC_12_TYPE_ID, MISSILE_TYPE_ID, RADAR_TYPE_ID, SAM_SITE_TYPE_ID, SOF_TEAM_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, SUBMARINE_TYPE_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, TANK_COMPANY_TYPE_ID, TRANSPORT_TYPE_ID } from '../../pieces/pieceId';

export const attackHeli: { [id: number]: number } = {};
attackHeli[BOMBER_TYPE_ID] = UNABLE_TO_HIT;
attackHeli[STEALTH_BOMBER_TYPE_ID] = UNABLE_TO_HIT;
attackHeli[STEALTH_FIGHTER_TYPE_ID] = UNABLE_TO_HIT;
attackHeli[AIR_REFUELING_SQUADRON_ID] = UNABLE_TO_HIT;
attackHeli[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = UNABLE_TO_HIT;
attackHeli[AIRBORN_ISR_TYPE_ID] = UNABLE_TO_HIT;
attackHeli[ARMY_INFANTRY_COMPANY_TYPE_ID] = 5;
attackHeli[ARTILLERY_BATTERY_TYPE_ID] = 4;
attackHeli[TANK_COMPANY_TYPE_ID] = 6;
attackHeli[MARINE_INFANTRY_COMPANY_TYPE_ID] = 5;
attackHeli[ATTACK_HELICOPTER_TYPE_ID] = 12;
attackHeli[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 4;
attackHeli[SAM_SITE_TYPE_ID] = 5;
attackHeli[DESTROYER_TYPE_ID] = 8;
attackHeli[A_C_CARRIER_TYPE_ID] = 9;
attackHeli[SUBMARINE_TYPE_ID] = UNABLE_TO_HIT;
attackHeli[TRANSPORT_TYPE_ID] = 9;
attackHeli[MC_12_TYPE_ID] = 6;
attackHeli[C_130_TYPE_ID] = 7;
attackHeli[SOF_TEAM_TYPE_ID] = 4;
attackHeli[RADAR_TYPE_ID] = 5;
attackHeli[MISSILE_TYPE_ID] = UNABLE_TO_HIT;
