// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';

export const marineInfantry: { [id: number]: number } = {};
marineInfantry[BOMBER_TYPE_ID] = 0;
marineInfantry[STEALTH_BOMBER_TYPE_ID] = 0;
marineInfantry[STEALTH_FIGHTER_TYPE_ID] = 0;
marineInfantry[AIR_REFUELING_SQUADRON_ID] = 0;
marineInfantry[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = 0;
marineInfantry[AIRBORN_ISR_TYPE_ID] = 0;
marineInfantry[ARMY_INFANTRY_COMPANY_TYPE_ID] = 6;
marineInfantry[ARTILLERY_BATTERY_TYPE_ID] = 5;
marineInfantry[TANK_COMPANY_TYPE_ID] = 9;
marineInfantry[MARINE_INFANTRY_COMPANY_TYPE_ID] = 7;
marineInfantry[ATTACK_HELICOPTER_TYPE_ID] = 11;
marineInfantry[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 8;
marineInfantry[SAM_SITE_TYPE_ID] = 4;
marineInfantry[DESTROYER_TYPE_ID] = 0;
marineInfantry[A_C_CARRIER_TYPE_ID] = 0;
marineInfantry[SUBMARINE_TYPE_ID] = 0;
marineInfantry[TRANSPORT_TYPE_ID] = 0;
marineInfantry[MC_12_TYPE_ID] = 12;
marineInfantry[C_130_TYPE_ID] = 12;
marineInfantry[SOF_TEAM_TYPE_ID] = 5;
marineInfantry[RADAR_TYPE_ID] = 7;
marineInfantry[MISSILE_TYPE_ID] = 0;
