export const AIRFIELD_0_LOCATION = 21; // Dragon Bottom
export const AIRFIELD_1_LOCATION = 70; // Dragon Top
export const AIRFIELD_2_LOCATION = 92; // HR Republic
export const AIRFIELD_3_LOCATION = 197; // Montaville
export const AIRFIELD_4_LOCATION = 253; // Lion
export const AIRFIELD_5_LOCATION = 372; // Fuller
export const AIRFIELD_6_LOCATION = 383; // Rico
export const AIRFIELD_7_LOCATION = 626; // Keoni
export const AIRFIELD_8_LOCATION = 640; // Eagle Bottom
export const AIRFIELD_9_LOCATION = 721; // Eagle Top

export const ALL_AIRFIELD_LOCATIONS = [
    AIRFIELD_0_LOCATION,
    AIRFIELD_1_LOCATION,
    AIRFIELD_2_LOCATION,
    AIRFIELD_3_LOCATION,
    AIRFIELD_4_LOCATION,
    AIRFIELD_5_LOCATION,
    AIRFIELD_6_LOCATION,
    AIRFIELD_7_LOCATION,
    AIRFIELD_8_LOCATION,
    AIRFIELD_9_LOCATION
];

export type ALL_AIRFIELD_LOCATIONS_TYPE =
    | typeof AIRFIELD_0_LOCATION
    | typeof AIRFIELD_1_LOCATION
    | typeof AIRFIELD_2_LOCATION
    | typeof AIRFIELD_3_LOCATION
    | typeof AIRFIELD_4_LOCATION
    | typeof AIRFIELD_5_LOCATION
    | typeof AIRFIELD_6_LOCATION
    | typeof AIRFIELD_7_LOCATION
    | typeof AIRFIELD_8_LOCATION
    | typeof AIRFIELD_9_LOCATION;
