export const AIRFIELD_1_LOCATION = 21;
export const AIRFIELD_2_LOCATION = 70;
export const AIRFIELD_3_LOCATION = 92;
export const AIRFIELD_4_LOCATION = 197;
export const AIRFIELD_5_LOCATION = 253;
export const AIRFIELD_6_LOCATION = 372;
export const AIRFIELD_7_LOCATION = 383;
export const AIRFIELD_8_LOCATION = 626;
export const AIRFIELD_9_LOCATION = 640;
export const AIRFIELD_10_LOCATION = 721;

export const ALL_AIRFIELD_LOCATIONS = [
    AIRFIELD_1_LOCATION,
    AIRFIELD_2_LOCATION,
    AIRFIELD_3_LOCATION,
    AIRFIELD_4_LOCATION,
    AIRFIELD_5_LOCATION,
    AIRFIELD_6_LOCATION,
    AIRFIELD_7_LOCATION,
    AIRFIELD_8_LOCATION,
    AIRFIELD_9_LOCATION,
    AIRFIELD_10_LOCATION
];
