export const MISSILE_SILO_1_LOCATION = 91;
export const MISSILE_SILO_2_LOCATION = 117;
export const MISSILE_SILO_3_LOCATION = 226;
export const MISSILE_SILO_4_LOCATION = 394;
export const MISSILE_SILO_5_LOCATION = 469;
export const MISSILE_SILO_6_LOCATION = 491;
export const MISSILE_SILO_7_LOCATION = 617;
export const MISSILE_SILO_8_LOCATION = 630;

export const ALL_MISSILE_SILO_LOCATIONS = [
    MISSILE_SILO_1_LOCATION,
    MISSILE_SILO_2_LOCATION,
    MISSILE_SILO_3_LOCATION,
    MISSILE_SILO_4_LOCATION,
    MISSILE_SILO_5_LOCATION,
    MISSILE_SILO_6_LOCATION,
    MISSILE_SILO_7_LOCATION,
    MISSILE_SILO_8_LOCATION
];
