export const MISSILE_SILO_1_LOCATION = 91; // HR Republic
export const MISSILE_SILO_2_LOCATION = 117; // Dragon
export const MISSILE_SILO_3_LOCATION = 226; // Noyarc
export const MISSILE_SILO_4_LOCATION = 394; // Fuller
export const MISSILE_SILO_5_LOCATION = 469; // Tamu
export const MISSILE_SILO_6_LOCATION = 491; // Shor Left
export const MISSILE_SILO_7_LOCATION = 617; // Eagle
export const MISSILE_SILO_8_LOCATION = 630; // Shor Right

export const ALL_MISSILE_SILO_LOCATIONS = [
    MISSILE_SILO_1_LOCATION,
    MISSILE_SILO_2_LOCATION,
    MISSILE_SILO_3_LOCATION,
    MISSILE_SILO_4_LOCATION,
    MISSILE_SILO_5_LOCATION,
    MISSILE_SILO_6_LOCATION,
    MISSILE_SILO_7_LOCATION,
    MISSILE_SILO_8_LOCATION
];
