// prettier-ignore
import { BOMBER_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, AIR_REFUELING_SQUADRON_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, AIRBORN_ISR_TYPE_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, TANK_COMPANY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, SAM_SITE_TYPE_ID, DESTROYER_TYPE_ID, A_C_CARRIER_TYPE_ID, SUBMARINE_TYPE_ID, TRANSPORT_TYPE_ID, MC_12_TYPE_ID, C_130_TYPE_ID, SOF_TEAM_TYPE_ID, RADAR_TYPE_ID, MISSILE_TYPE_ID } from '../../pieces/pieceId';

export const aircraftCarrier: { [id: number]: number } = {};
aircraftCarrier[BOMBER_TYPE_ID] = 9;
aircraftCarrier[STEALTH_BOMBER_TYPE_ID] = 1;
aircraftCarrier[STEALTH_FIGHTER_TYPE_ID] = 1;
aircraftCarrier[AIR_REFUELING_SQUADRON_ID] = 3;
aircraftCarrier[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = 2;
aircraftCarrier[AIRBORN_ISR_TYPE_ID] = 4;
aircraftCarrier[ARMY_INFANTRY_COMPANY_TYPE_ID] = 0;
aircraftCarrier[ARTILLERY_BATTERY_TYPE_ID] = 0;
aircraftCarrier[TANK_COMPANY_TYPE_ID] = 0;
aircraftCarrier[MARINE_INFANTRY_COMPANY_TYPE_ID] = 0;
aircraftCarrier[ATTACK_HELICOPTER_TYPE_ID] = 3;
aircraftCarrier[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = 0;
aircraftCarrier[SAM_SITE_TYPE_ID] = 0;
aircraftCarrier[DESTROYER_TYPE_ID] = 2;
aircraftCarrier[A_C_CARRIER_TYPE_ID] = 4;
aircraftCarrier[SUBMARINE_TYPE_ID] = 2;
aircraftCarrier[TRANSPORT_TYPE_ID] = 4;
aircraftCarrier[MC_12_TYPE_ID] = 6;
aircraftCarrier[C_130_TYPE_ID] = 5;
aircraftCarrier[SOF_TEAM_TYPE_ID] = 0;
aircraftCarrier[RADAR_TYPE_ID] = 0;
aircraftCarrier[MISSILE_TYPE_ID] = 0;
