import { UNABLE_TO_HIT } from '../../globals';
// prettier-ignore
import { AIRBORN_ISR_TYPE_ID, AIR_REFUELING_SQUADRON_ID, ARMY_INFANTRY_COMPANY_TYPE_ID, ARTILLERY_BATTERY_TYPE_ID, ATTACK_HELICOPTER_TYPE_ID, A_C_CARRIER_TYPE_ID, BOMBER_TYPE_ID, C_130_TYPE_ID, DESTROYER_TYPE_ID, LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID, MARINE_INFANTRY_COMPANY_TYPE_ID, MC_12_TYPE_ID, MISSILE_TYPE_ID, RADAR_TYPE_ID, SAM_SITE_TYPE_ID, SOF_TEAM_TYPE_ID, STEALTH_BOMBER_TYPE_ID, STEALTH_FIGHTER_TYPE_ID, SUBMARINE_TYPE_ID, TACTICAL_AIRLIFT_SQUADRON_TYPE_ID, TANK_COMPANY_TYPE_ID, TRANSPORT_TYPE_ID } from '../../pieces/pieceId';

export const submarine: { [id: number]: number } = {};
submarine[BOMBER_TYPE_ID] = UNABLE_TO_HIT;
submarine[STEALTH_BOMBER_TYPE_ID] = UNABLE_TO_HIT;
submarine[STEALTH_FIGHTER_TYPE_ID] = UNABLE_TO_HIT;
submarine[AIR_REFUELING_SQUADRON_ID] = UNABLE_TO_HIT;
submarine[TACTICAL_AIRLIFT_SQUADRON_TYPE_ID] = UNABLE_TO_HIT;
submarine[AIRBORN_ISR_TYPE_ID] = UNABLE_TO_HIT;
submarine[ARMY_INFANTRY_COMPANY_TYPE_ID] = UNABLE_TO_HIT;
submarine[ARTILLERY_BATTERY_TYPE_ID] = UNABLE_TO_HIT;
submarine[TANK_COMPANY_TYPE_ID] = UNABLE_TO_HIT;
submarine[MARINE_INFANTRY_COMPANY_TYPE_ID] = UNABLE_TO_HIT;
submarine[ATTACK_HELICOPTER_TYPE_ID] = UNABLE_TO_HIT;
submarine[LIGHT_INFANTRY_VEHICLE_CONVOY_TYPE_ID] = UNABLE_TO_HIT;
submarine[SAM_SITE_TYPE_ID] = UNABLE_TO_HIT;
submarine[DESTROYER_TYPE_ID] = 5;
submarine[A_C_CARRIER_TYPE_ID] = 5;
submarine[SUBMARINE_TYPE_ID] = 7;
submarine[TRANSPORT_TYPE_ID] = 6;
submarine[MC_12_TYPE_ID] = UNABLE_TO_HIT;
submarine[C_130_TYPE_ID] = UNABLE_TO_HIT;
submarine[SOF_TEAM_TYPE_ID] = UNABLE_TO_HIT;
submarine[RADAR_TYPE_ID] = UNABLE_TO_HIT;
submarine[MISSILE_TYPE_ID] = UNABLE_TO_HIT;
